### ISSUE TITLE
Support pyodbc with SQL 18 server

### ISSUE THREAD

**Issue by LauJohansson** [spetlr-org/spetlr#128]
## This issue is a ...

- Feature request

## Initial description
Since the newer cluster (13.3+ LTS) versions needs v18, we need to make it possible to alter the driver settings.

## What is the current behavior?
In the moment spetlr only support v17. 

## What is the expected behavior?
support v7 and 18

## Proposed solution or approach
If unicty catalog is enabled:
https://packages.microsoft.com/ubuntu/22.04/prod/pool/main/m/msodbcsql18/
download [msodbcsql18_18.3.2.1-1_amd64.deb](https://packages.microsoft.com/ubuntu/22.04/prod/pool/main/m/msodbcsql18/msodbcsql18_18.3.2.1-1_amd64.deb)
put into volume (lake)

sudo ACCEPT_EULA=Y apt-get install -q -y /Volumes/dataplatform/deployment/init_scripts/msodbcsql18_18.3.2.1-1_amd64.deb

**Comment by FarBo** [comment]
This is covered in thos PR:
#177 
Still UC is not enabled and we have put the driver to dbfs location
