### ISSUE TITLE
Pypi 2FA enable

### ISSUE THREAD

**Issue by LauJohansson** [spetlr-org/spetlr#46]
https://www.bleepingcomputer.com/news/security/pypi-announces-mandatory-use-of-2fa-for-all-software-publishers/
https://thehackernews.com/2023/05/pypi-implements-mandatory-two-factor.html
https://thehackernews.com/2022/07/pypi-repository-makes-2af-security.html

**Comment by mrmasterplan** [comment]
This needs attention. Should be top of our list.

**Comment by mrmasterplan** [comment]
Have a look at #99 This was actually a really simple fix.

**Comment by mrmasterplan** [comment]
For future reference: https://blog.pypi.org/posts/2023-04-20-introducing-trusted-publishers/
