### ISSUE TITLE
End support for LTS 9.1

### ISSUE THREAD

**Issue by mrmasterplan** [spetlr-org/spetlr#61]
Let's end support for LTS 9.1 and also for python 3.8. Lowest supported version will then be 10.4. Please leave a comment if you agree.

**Comment by LauJohansson** [comment]
Agree.

**Comment by mrmasterplan** [comment]
The end of support for Databricks runtime 9.1 LTS will end on the 15th of September 2023. Please leave a comment if you still need support after that.
