### ISSUE TITLE
It is not possible to load data to sql server if dataframe has early dates

### ISSUE THREAD

**Issue by FarBo** [spetlr-org/spetlr#64]
Sql server min allowed date is 1753-01-01. If the dataframe has a timestamp column that has values lower tahn this date, it is not possible to load the data to the sql server.

Suggestion:
SimpleSqlServerTransformer needs to convert those early dates to a value that is acceptable by the sql server.

**Comment by LauJohansson** [comment]
@FarBo  should this be closed?

**Comment by FarBo** [comment]
This is handled in this PR #65
